// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiThiNVH.Migrations
{
    [DbContext(typeof(NVH))]
    [Migration("20230629021032_Create_Table_NVHCau3")]
    partial class Create_Table_NVHCau3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("BaiThiNVH.Models.NVHCau3", b =>
                {
                    b.Property<string>("Ten")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lop")
                        .HasColumnType("TEXT");

                    b.HasKey("Ten");

                    b.ToTable("NVHCau3");
                });
#pragma warning restore 612, 618
        }
    }
}
